train: true
model: "yolo12n.pt"

project: "EyeInTheSky"
dataset_name: "VisDrone"

raw_data_dir: "data/raw"
data_dir: "data"
config_dir: "config"
interim_data_dir: "data/interim"
processed_data_dir: "data/processed"
external_data_dir: "data/external"
models_dir: "models"
reports_dir: "reports"
figures_dir: "reports/figures"

train:
  model: "yolo12n"
  project: "EyeInTheSky"
  data: "VisDrone.yaml"
  task: detect
  device: 0
  epochs: 1
  batch: 16
  workers: 8
  seed: 42
  plots: True
  imgsz: 640
  exist_ok: False
  save: True
  save_period: 10
  val: True
  warmup_epochs: 10
  visualize: True
  show: True
  single_cls: False # (bool) train multi-class data as single-class
  rect: False # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
  cos_lr: False # (bool) use cosine learning rate scheduler
  resume: False # (bool) resume training from last checkpoint
  amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
  fraction: 1.0 # (float) dataset fraction to train on (default is 1.0, all images in train set)
  freeze: None # (int | list, optional) freeze first n layers, or freeze list of layer indices during training
  cache: False
val:
  project: "EyeInTheSky"
  name: "YOLOv12-VisDrone-Validation"
  half: True
  conf: 0.25
  iou: 0.6
  split: "test"
  rect: True
  plots: True

tune:
  name: "YOLOv12-VisDrone-Tuning"
  epochs: 20
  iterations: 40
  batch: 8
  workers: 4
  seed: 42
  cos_lr: True
  plots: True
  val: True
  use_ray: True
  imgsz: 640
  exist_ok: False
  save: True
  save_period: 10
  cache: "disk"

wandb:
  dir: "reports/"

# Merged class names (after merging 'people' into 'pedestrian')
names:
  0: person
  1: bicycle
  2: car
  3: van
  4: truck
  5: tricycle
  6: awning-tricycle
  7: bus
  8: motor

# Translations
translations:
  italian:
    0: persona
    1: bicicletta
    2: auto
    3: furgone
    4: camion
    5: triciclo
    6: triciclo-tendalino
    7: autobus
    8: motore