model: "yolo12n"
wandb_project: "EyeInTheSky_merged"
data: "VisDrone.yaml"
train:
  model: "yolo12n"
  project: "EyeInTheSky"
  data: "VisDrone.yaml"
  device: 0
  task: detect
  epochs: 300
  batch: 16
  workers: 8
  seed: 42
  plots: True
  imgsz: 640
  exist_ok: False
  save: True
  save_period: 10
  val: True
  warmup_epochs: 10
  visualize: True
  show: True
  single_cls: False # (bool) train multi-class data as single-class
  rect: False # (bool) rectangular training if mode='train' or rectangular validation if mode='val'
  cos_lr: False
  resume: False
  amp: True # (bool) Automatic Mixed Precision (AMP) training, choices=[True, False], True runs AMP check
  fraction: 1.0
  freeze: None
  cache: False
val:
  project: "EyeInTheSky"
  name: "YOLOv12-VisDrone-Validation"
  half: True
  conf: 0.25
  iou: 0.6
  split: "test"
  rect: True
  plots: True
  visualize: True