train: true
model_name: "yolo12n"

project_name: "EyeInTheSky"
dataset_name: "VisDrone"

raw_data_dir: "data/raw"
data_dir: "data"
config_dir: "config"
interim_data_dir: "data/interim"
processed_data_dir: "data/processed"
external_data_dir: "data/external"
models_dir: "models"
reports_dir: "reports"
figures_dir: "reports/figures"

# Ray Tune Configuration
shared_args:
  workers: 8               # Number of data loader workers
  seed: 42                 # Random seed
  exist_ok: False          # Don't increment run if exists
  cos_lr: True            # Cosine learning rate
  imgsz: 640               # Input image size
  plots: True
  patience: 5             # Early stopping patience
  val: False

# Fixed Training Configuration
train:
  project: "models"
  name: "YOLOv12-VisDrone-Training"
  epochs: 10             # Number of training epochs
  save: False              # Save checkpoints
  save_period: 10         # Save every X epochs

val:
  half: True
  conf: 0.25
  iou: 0.6

tune:
  fixed_args:
    project: "models"
    name: "YOLOv12-VisDrone-Tuning"
    iterations: 10
    use_ray: True
    grace_period: 10 
    warmup_epochs: 0        # Warmup epochs
    save: True             # Save checkpoints
    save_period: 10        # Save every X epochs
    epochs: 10             # Number of training epochs

  space:
    optimizer: ['adamw', 'SGD']  
    lr0: [0.00001, 0.00005, 0.0001]     # Keep it low for fine-tuning
    momentum: [0.9, 0.95, 0.98]          # High momentum for stability
    weight_decay: [0.0, 0.0001]          # Minimal regularization
    cls: [0.5, 1, 1.5]           # Higher cls weights to improve classification

wandb:
  dir: "reports/wandb"